services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: aegistic
      POSTGRES_USER: aegistic
      POSTGRES_PASSWORD: aegistic
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://aegistic:aegistic@db:5432/aegistic
      NODE_ENV: production
    depends_on:
      - db
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      # - "443:443"  # enable if you add certs
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
