services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aegistic}
      POSTGRES_USER: ${POSTGRES_USER:-aegistic}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aegistic}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ..
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-aegistic}:${POSTGRES_PASSWORD:-aegistic}@db:5432/${POSTGRES_DB:-aegistic}
      NODE_ENV: production
    depends_on:
      - db
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
