name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm i --no-frozen-lockfile
      - run: pnpm prisma generate
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: next-standalone
          path: |
            .next
            public
            package.json
            node_modules
            prisma
